-- Add bus check-in/check-out tracking columns expected by the API.
-- Safe to run multiple times.

ALTER TABLE delegates
  ADD COLUMN IF NOT EXISTS opening_ceremony_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS opening_ceremony_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day1_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day1_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day2_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day2_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day3_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day3_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day4_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day4_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS performance_day_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS performance_day_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS conf_day1_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS conf_day1_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS conf_day2_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS conf_day2_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS conf_day3_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS conf_day3_bus_checkout TIMESTAMP WITH TIME ZONE;

ALTER TABLE members
  ADD COLUMN IF NOT EXISTS opening_ceremony_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS opening_ceremony_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day1_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day1_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day2_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day2_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day3_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day3_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day4_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS day4_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS performance_day_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS performance_day_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS conf_day1_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS conf_day1_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS conf_day2_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS conf_day2_bus_checkout TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS conf_day3_bus_checkin TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS conf_day3_bus_checkout TIMESTAMP WITH TIME ZONE;
